# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ComId', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=100)),
                ('PostId', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.CharField(max_length=1000000)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Catagory')),
            ],
        ),
    ]
